Repository ultimatemember/ultimatemember, pull requests merged in 2021-03, with the labels that each got.

#709 Indexing of Profiles
  includes/admin/core/class-admin-settings.php
  includes/admin/templates/role/profile.php
  includes/core/class-builtin.php
  includes/core/class-user.php
  includes/core/um-actions-profile.php
  includes/core/um-filters-account.php
Labels: feature request

#719 Fix NaN in the slider range.
  includes/core/class-member-directory.php
Labels: bug

#768 jQuery 3 compatibility (for WordPress 5.7 and higher)
  assets/js/um-conditional.js
  assets/js/um-functions.js
  assets/js/um-jquery-form.js
  assets/js/um-members.js
  assets/js/um-profile.js
  assets/js/um-scripts.js
  includes/admin/assets/js/um-admin-dragdrop.js
  includes/admin/assets/js/um-admin-field.js
  includes/admin/assets/js/um-admin-form.js
  includes/admin/assets/js/um-admin-forms.js
  includes/admin/assets/js/um-admin-role-wrapper.js
  includes/admin/assets/js/um-admin-scripts.js
  includes/admin/assets/js/um-admin-settings.js
  includes/core/class-user.php
Labels: tag: enhancement 💯
