Repository ultimatemember/ultimatemember, pull requests merged in 2021-04, with the labels that each got.

#804 Activation link expiration
  includes/admin/core/class-admin-settings.php
  includes/class-config.php
  includes/core/class-permalinks.php
  includes/core/class-user.php
Labels: tag: enhancement 💯, v2.0

#807 Private profiles editing
  includes/core/class-roles-capabilities.php
  includes/core/um-actions-profile.php
  includes/um-short-functions.php
  readme.txt
Labels: bug, tag: enhancement 💯, v2.0

#814 JavaScript error in the members directory filter
  assets/js/um-scripts.js
  assets/js/um-scripts.min.js
Labels: bug
