Repository ultimatemember/ultimatemember, pull requests merged in 2022-08, with the labels that each got.

#1057 Extend site health
  modules/forumwp/includes/admin/class-site-health.php
  modules/jobboardwp/includes/admin/class-site-health.php
  modules/member-directory/includes/admin/class-site-health.php
Labels: v3

#1062 - fixed issue with visible ID in password reset link and form
  includes/core/class-password.php
  includes/core/class-user.php
  includes/core/um-actions-account.php
  templates/password-change.php
  templates/password-reset.php
Labels: v2.0, dev-flow: test waiting, issue-type: standard

#1067 - fixed text filter label on the member directory;
  includes/core/class-member-directory.php
Labels: v2.0, tag: needs investigation 👀, dev-flow: test waiting
