Repository ultimatemember/ultimatemember, pull requests merged in 2023-02, with the labels that each got.

#1119 Fix php warning if empty password
  includes/core/um-actions-form.php
Labels: issue-type: small

#1111 Development 2.5.4
  README.md
  assets/img/extensions/bbpress.png
  assets/img/extensions/bbpress.svg
  assets/img/extensions/followers.png
  assets/img/extensions/followers.svg
  assets/img/extensions/friends.png
  assets/img/extensions/friends.svg
  assets/img/extensions/groups.png
  assets/img/extensions/groups.svg
  assets/img/extensions/mailchimp.png
  assets/img/extensions/notices.png
  assets/img/extensions/notices.svg
  assets/img/extensions/online-users.png
  assets/img/extensions/online-users.svg
  assets/img/extensions/private-content.png
  assets/img/extensions/private-content.svg
  assets/img/extensions/private-messages.png
  assets/img/extensions/private-messages.svg
  assets/img/extensions/profile-completeness.png
  assets/img/extensions/profile-completeness.svg
  assets/img/extensions/profile-tabs.png
  assets/img/extensions/profile-tabs.svg
  assets/img/extensions/real-time-notifications.png
  assets/img/extensions/real-time-notifications.svg
  assets/img/extensions/social-activity.png
  assets/img/extensions/social-activity.svg
  assets/img/extensions/social-login.png
  assets/img/extensions/social-login.svg
  assets/img/extensions/terms-conditions.png
  assets/img/extensions/terms-conditions.svg
  assets/img/extensions/unsplash.png
  assets/img/extensions/user-bookmarks.png
  assets/img/extensions/user-bookmarks.svg
  assets/img/extensions/user-locations.png
  assets/img/extensions/user-locations.svg
  assets/img/extensions/user-notes.png
  assets/img/extensions/user-notes.svg
  assets/img/extensions/user-photos.png
  assets/img/extensions/user-photos.svg
  assets/img/extensions/user-reviews.png
  assets/img/extensions/user-reviews.svg
  assets/img/extensions/user-tags.png
  assets/img/extensions/user-tags.svg
  assets/img/extensions/verified-users.png
  assets/img/extensions/verified-users.svg
  assets/img/extensions/woocommerce.png
  includes/admin/assets/css/um-admin-dashboard.css
  includes/admin/core/class-admin-notices.php
  includes/admin/templates/extensions.php
  includes/class-functions.php
  includes/core/class-access.php
  includes/core/class-builtin.php
  includes/core/class-fields.php
  includes/core/class-form.php
  includes/core/um-actions-form.php
  includes/core/um-filters-fields.php
  readme.txt
  templates/profile.php
  templates/restricted-blog.php
  ultimate-member.php
Labels: v2.0

#1136 social links colors
  includes/core/class-builtin.php
Labels: tag: needs investigation 👀
