Repository ultimatemember/ultimatemember, pull requests merged in 2023-12, with the labels that each got.

#1380 Security report 4
  includes/core/class-access.php
Labels: v2.0, tag: needs investigation 👀

#1386 Cropper.JS case with invalid init
  assets/js/um-modal.js
  assets/js/um-modal.min.js
Labels: v2.0, dev-flow: test waiting

#1379 Version 2.8.1
  README.md
  assets/css/admin/settings.css
  assets/css/admin/settings.min.css
  assets/css/admin/settings.sass
  assets/js/um-modal.js
  assets/js/um-modal.min.js
  includes/admin/class-site-health.php
  includes/admin/core/class-admin-forms.php
  includes/admin/core/class-admin-notices.php
  includes/admin/core/class-admin-settings.php
  includes/admin/templates/extensions.php
  includes/core/class-access.php
  includes/core/class-builtin.php
  includes/core/class-setup.php
  includes/core/um-filters-navmenu.php
  readme.txt
  ultimate-member.php
Labels: v2.0
