Repository ultimatemember/ultimatemember, pull requests merged in 2024-01, with the labels that each got.

#1388 Spelling
  includes/admin/core/class-admin-metabox.php
  includes/admin/templates/access/restrict_content.php
Labels: v2.0, tag: enhancement 💯, issue-type: small

#1413 MegaMenu and conditional handlers
  includes/core/um-filters-navmenu.php
Labels: v2.0, dev-flow: test waiting, issue-type: small

#1375 Shortcode to display profile link.
  includes/core/class-shortcodes.php
Labels: feature request, v2.0, tag: needs investigation 👀

#1396 Version 2.8.2
  README.md
  assets/css/admin/builder.css
  assets/css/admin/builder.min.css
  assets/css/admin/builder.sass
  assets/css/admin/common.css
  assets/css/admin/common.min.css
  assets/css/admin/common.sass
  assets/css/admin/forms.css
  assets/css/admin/forms.min.css
  assets/css/admin/forms.sass
  assets/css/common.css
  assets/css/common.min.css
  assets/css/common.sass
  assets/css/um-account.css
  assets/css/um-account.min.css
  assets/css/um.rtl.css
  assets/css/um.rtl.min.css
  assets/js/admin/forms.js
  assets/js/admin/forms.min.js
  assets/js/common-frontend.js
  assets/js/common-frontend.min.js
  assets/js/common.js
  assets/js/common.min.js
  assets/js/um-members.js
  assets/js/um-members.min.js
  assets/js/um-responsive.js
  assets/js/um-responsive.min.js
  includes/admin/core/class-admin-metabox.php
  includes/admin/core/class-admin-navmenu.php
  includes/admin/core/class-admin-settings.php
  includes/admin/templates/access/restrict_content.php
  includes/common/class-enqueue.php
  includes/core/class-access.php
  includes/core/class-fields.php
  includes/core/class-member-directory.php
  includes/core/class-shortcodes.php
  includes/core/um-filters-fields.php
  includes/core/um-filters-navmenu.php
  includes/frontend/class-enqueue.php
  readme.txt
  templates/profile/posts-single.php
  ultimate-member.php
Labels: v2.0, dev-flow: in progress

#1408 Ultimate Member > Settings redesign
  assets/css/admin/forms.css
  assets/css/admin/forms.min.css
  assets/css/admin/forms.sass
  assets/css/admin/settings.css
  assets/css/admin/settings.min.css
  assets/css/admin/settings.sass
  assets/js/admin/forms.js
  assets/js/admin/forms.min.js
  includes/admin/class-admin.php
  includes/admin/class-enqueue.php
  includes/admin/class-secure.php
  includes/admin/core/class-admin-forms-settings.php
  includes/admin/core/class-admin-forms.php
  includes/admin/core/class-admin-menu.php
  includes/admin/core/class-admin-notices.php
  includes/admin/core/class-admin-settings.php
  includes/admin/core/list-tables/emails-list-table.php
  includes/admin/core/list-tables/version-template-list-table.php
  includes/ajax/class-init.php
  includes/ajax/class-pages.php
  includes/ajax/class-secure.php
  includes/class-config.php
  includes/class-init.php
  includes/core/class-options.php
  includes/lib/browser.php
  includes/um-core-functions.php
Labels: v2.0, dev-flow: in progress, issue-type: major
